<?php 
//Apple Weather

//Погода для России http://servisvk.ru/status/pogoda/russia.php

//if ($_SERVER['REQUEST_URI']=='/v1/yql...') : 
header('Content-Type: text/xml'); ?>
<?xml version="1.0" encoding="UTF-8"?>
<query xmlns:yahoo="http://www.yahooapis.com/v1/base.rng" yahoo:count="2" yahoo:created="2015-10-01T12:38:19Z" yahoo:lang="ru"><meta><meta><weather><yahoo_mobile_url>http://m.yahoo.com/?.tsrc=appleww&amp;.lang=ru</yahoo_mobile_url><twc_mobile_url>http://itunes.apple.com/us/app/the-weather-channel/id295646461?mt=8&amp;uo=4</twc_mobile_url><units distanceUnits="km" pressureUnits="mb" speedUnits="km/h" tempUnits="C"/></weather></meta><meta><weather><yahoo_mobile_url>http://m.yahoo.com/?.tsrc=appleww&amp;.lang=ru</yahoo_mobile_url><twc_mobile_url>http://itunes.apple.com/us/app/the-weather-channel/id295646461?mt=8&amp;uo=4</twc_mobile_url><units tempUnits="C"/></weather></meta></meta><results><results><location city="Москва" country="Россия" latitude="55.45" locationID="RSXX0063" longitude="37.36" state="Московская Область" woeid="2346910"><proximateStation ID="RSXX0063" city="Moscow"/><currently moonfacevisible="85.7%" moonphase="5" sunrise24="05:38" sunset24="17:15" temp="14" time24="14:59" timezone="GMT+3"><condition code="34"/></currently><forecast><day dayOfWeek="5" poP="0"><temp high="17" low="6"/><condition code="32"/></day><day dayOfWeek="6" poP="70"><temp high="12" low="9"/><condition code="11"/></day><day dayOfWeek="7" poP="10"><temp high="16" low="6"/><condition code="24"/></day><day dayOfWeek="1" poP="0"><temp high="12" low="2"/><condition code="30"/></day><day dayOfWeek="2" poP="0"><temp high="15" low="7"/><condition code="34"/></day><day dayOfWeek="3" poP="40"><temp high="14" low="3"/><condition code="39"/></day><extended_forecast_url>http://m.yahoo.com/search?p=Москва,+Московская+Область&amp;.tsrc=appleww&amp;.lang=ru</extended_forecast_url></forecast></location></results><results><location woeid="2346910"><hourlyforecast><hour time24="17:00"><condition code="32" poP="0" temp="12"/></hour><hour time24="18:00"><condition code="32" poP="0" temp="11"/></hour><hour time24="19:00"><condition code="31" poP="0" temp="9"/></hour><hour time24="20:00"><condition code="31" poP="0" temp="9"/></hour><hour time24="21:00"><condition code="31" poP="0" temp="9"/></hour><hour time24="22:00"><condition code="31" poP="0" temp="8"/></hour><hour time24="23:00"><condition code="31" poP="0" temp="8"/></hour><hour time24="00:00"><condition code="31" poP="0" temp="8"/></hour><hour time24="01:00"><condition code="31" poP="0" temp="8"/></hour><hour time24="02:00"><condition code="31" poP="0" temp="8"/></hour><hour time24="03:00"><condition code="33" poP="0" temp="7"/></hour><hour time24="04:00"><condition code="29" poP="0" temp="7"/></hour></hourlyforecast></location></results></results></query><!-- total: 5 -->
<!-- engine1151.yql.bf1.yahoo.com -->
<?php //endif; ?>